#!/usr/bin/env sh

OBSIDIAN_PATH="$HOME/repos/tasks"

cd $OBSIDIAN_PATH

CHANGES_EXIST="$(git status - porcelain | wc -l)"

if [ "$CHANGES_EXIST" -eq 0 ]; then
    exit 0
fi

/usr/bin/git pull
/usr/bin/git add .
/usr/bin/git commit -q -m "Last Sync: $(date +"%Y-%m-%d %H:%M:%S")"
/usr/bin/git push -q
