#!/bin/bash

battery_percent=$(("$(cat "/sys/class/power_supply/BAT0/energy_now") * 100 /$(cat "/sys/class/power_supply/BAT0/energy_full")"))
charging_status=$(cat "/sys/class/power_supply/BAT0/status")
if [[ "$charging_status" = "Charging" ]]; then
	battery_icon=""
elif [[ "$charging_status" = "Discharging" ]]; then
	battery_icons=("" "" "" "" "" "" "" "" "" "" "")
	battery_icon=${battery_icons[$(($battery_percent / 10))]}
else
	battery_icon=" "
fi

printf "%s %s%%" $battery_icon $battery_percent | tee /tmp/batterystatus

